/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.util.Locale;

/**
 *
 * @author migfe
 */
public class ini extends javax.swing.JFrame {

    /**
     * Creates new form ini
     */
    public ini() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSalir = new javax.swing.JButton();
        jNombreUser = new javax.swing.JLabel();
        jPassUsuario = new javax.swing.JLabel();
        jNombretxt = new javax.swing.JTextField();
        jPasstxt = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jIniciar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(470, 550));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images&icons/nuevo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 170, 230));

        jSalir.setBackground(java.awt.Color.green);
        jSalir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jNombreUser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jNombreUser.setText("Usuario:");
        getContentPane().add(jNombreUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        jPassUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPassUsuario.setText("Contraseña:");
        getContentPane().add(jPassUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        jNombretxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(jNombretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 140, -1));

        jPasstxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(jPasstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 140, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        jLabel2.setText("Inicio de Sesión");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jIniciar.setBackground(java.awt.Color.green);
        jIniciar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images&icons/icons8-entrar-26.png"))); // NOI18N
        jIniciar.setText("Iniciar");
        jIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(jIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images&icons/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, -120, 750, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jSalirActionPerformed

    private void jIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ini().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jNombreUser;
    private javax.swing.JTextField jNombretxt;
    private javax.swing.JLabel jPassUsuario;
    private javax.swing.JPasswordField jPasstxt;
    private javax.swing.JButton jSalir;
    // End of variables declaration//GEN-END:variables
}
